# Generated by Django 5.0.2 on 2026-07-13 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgoraReferralClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('course_slug', models.CharField(max_length=200)),
                ('course_title', models.CharField(max_length=300)),
                ('destination_url', models.URLField(max_length=500)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Agora referral click',
                'verbose_name_plural': 'Agora referral clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='AgoraReferralConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyra_ref', models.CharField(db_index=True, max_length=64)),
                ('course_slug', models.CharField(blank=True, max_length=200)),
                ('event_type', models.CharField(default='enrollment', max_length=50)),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('click', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='website.agorareferralclick')),
            ],
            options={
                'verbose_name': 'Agora referral conversion',
                'verbose_name_plural': 'Agora referral conversions',
                'ordering': ['-converted_at'],
            },
        ),
    ]
